server:
  port: 9000
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
security:
  jwt:
    secret-key: verysecretkey12345